### ISSUE TITLE
i was added to the bytes leaderboard as "anonymous"

### ISSUE THREAD

**Issue by backwardspy** [coreyja/coreyja.com#121]
hi! i just did the first bytes question, really cool idea!

unfortunately, i seem to have been added to the leaderboard under the name "anonymous":

![image](https://github.com/user-attachments/assets/d9b50391-4074-45ea-8d5e-cf1f92389228)

i *think* i am the 293 there. i couldn't see any way to link my github account - is this a bug?

**Comment by coreyja** [comment]
> is this a bug?

Yes, yes it is!

When you solved the Byte did you get a JS dialog menu asking for your Github Username?

This is the 'expected' behavior if you leave that box blank

I'll go ahead and edit the DB manually now, but obv want to fix this!

**Comment by coreyja** [comment]
Ok DB edited and you are working now!

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/e5ebdce7-a14e-45e5-ad55-739d953d83c0">

Besides figuring out _why_ you didn't get a Username in there, I also need to fix the profile pic not working. Its trying to grab one from Github even for anonymous submits so need to adjust that logic!

**Comment by coreyja** [comment]
Chatted with the team that runs the actual iFrame embed there, and they confirmed its a bug where the dialog got lost when we made it possible to submit anonymously 😆 

So fix will be deployed this evening for that! Thanks for reporting it!!

I just assumed the other anonymous person _meant_ to do that but now very curious who it was (but oh well lol!)

**Comment by backwardspy** [comment]
yay! thanks for sorting that out :)

> When you solved the Byte did you get a JS dialog menu asking for your Github Username?

i did not. i just watched your video solving the first question, and i see now how the flow is supposed to go. unlike yours, when i hit submit it just showed me my score. i then navigated to the leaderboard, saw that same score next to "anonymous", and wondered if something odd had happened!
